[project]
version = "0.1.0" # bh.bump: this line must be first.
name = "bh-hostconfig"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bh-bump>=0.1.3rc1",
    "pytest>=8.3.3",
]
