#!/usr/bin/env bash
INSTALL=/INSTALL
LOG=/INSTALL/install.log
sudo mkdir -p ${INSTALL}
sudo touch $LOG
sudo chmod 777 $LOG

now () {
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    echo ${ts}
}

log () {
    echo $(now) : "$@" >> $LOG ;
}

run () {
    log "running: [$*]"
    $*
}

_install () {
     log "_install: $1 is at [$(which $1)]"
     which $1 && return
     run sudo apt install -y $1
     log "_install: $1 is at [$(which $1)]"
}

log "++ repo setup [$0] [$*]"
run export BASE=$1
run cd $(dirname $0)
run export REPO=${PWD}
log "BASE is ${BASE}"
log "REPO is ${REPO}"
log "PWD is [$PWD]"
log "tilde is [~]"
log "HOME is [$HOME]"
log "BASE is [$BASE]"
run sudo apt -f install
_install stow
_install mcrypt
_install gh
_install expect
log "-- repo setup [$0] [$*]"
