#!/usr/bin/env bash

BASE=/INSTALL
LOG=/INSTALL/install.log
sudo mkdir -p ${BASE}
sudo touch $LOG
sudo chmod 777 $LOG

now () {
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    echo ${ts}
}

log () {
    echo $(now) : "$@" >> $LOG ;
}

run () {
    log "running: [$*]"
    $*
}

_install () {
     log "_install: $1 is at [$(which $1)]"
     which $1 && return
     run sudo apt install -y $1
     log "_install: $1 is at [$(which $1)]"
}

log "++ outer [$0] [$*]"
run cd $(dirname $0)
log "outer: CWD is [${PWD}]"
run . ./install.d/setup.sh
log "-- outer [$0] [$*]"
